### ISSUE TITLE
can't intsall

### ISSUE THREAD

**Issue by jf2016GH** [kylessmith/ailist#3]
tried:
pip install ailist

got this error:
File ".../anaconda3/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 98, in set_language_level
        if level >= 3:
    TypeError: '>=' not supported between instances of 'str' and 'int'

**Comment by kylessmith** [comment]
I have pushed an update to the github version, not the pip version yet. Let me know if it fixes it.

**Comment by jf2016GH** [comment]
Just updated ailist for python.   

    On Wednesday, November 13, 2019, 1:22:50 PM EST, Kyle Smith <notifications@github.com> wrote:  
 
 
I have pushed an update to the github version, not the pip version yet. Let me know if it fixes it.
