### ISSUE TITLE
How is openmp used/planned to be used?

### ISSUE THREAD

**Issue by endrebak** [kylessmith/ailist#4]
I see that you have openmp flags in the setup.py. I was thinking of playing around with the ailist and openmp, see https://stackoverflow.com/questions/58802205/having-thread-local-arrays-in-cython-so-that-i-can-resize-them

Just wondering if you were going to try a parallel ailist version.

I will be using the next 6 months finishing up my PhD, but after that I would be interested in incorporating ailist into pyranges :) I really like your code, mine is just cargo-culting 😳

**Comment by kylessmith** [comment]
Congrats on finishing up your PhD!!!
I put the flags there because I was thinking about implementing a parallel query method that divides query arrays into chunks. I haven't put too much thought into it yet. Just kept the flags there in case.
